version: '3'

services:
  server:
    build: ./
    depends_on:
      - db
    volumes:
      - ./:/usr/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    command: npm run start-dev
  db: 
    image: "postgres:11"
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"